# Generated by Django 2.1.1 on 2019-08-03 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190803_0938'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='userBuyer',
            field=models.ManyToManyField(related_name='userBuyer', to='user.User', verbose_name='购买用户'),
        ),
        migrations.AddField(
            model_name='course',
            name='userShoppingcart',
            field=models.ManyToManyField(related_name='userShoppingcart_set', to='user.User', verbose_name='加入购物车用户'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='createDatetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 3, 9, 38, 17, 94825)),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
